# Generated by Django 4.2.7 on 2024-03-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('reg_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('mark', models.IntegerField()),
                ('course', models.CharField(max_length=40)),
                ('college', models.CharField(max_length=26)),
            ],
        ),
    ]
